kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: k8steam3file
provisioner: kubernetes.io/azure-disk
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
parameters:
  storageAccount: k8steam3sac
